[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.23.12" }
webpki-roots = "0.26"
hex = "0.4.2"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }