[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.23.12" }
tokio = { version = "1.34.0", features = ["io-util", "macros", "net", "rt"]}
webpki-roots = "0.26"